# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100

      - name: Download CP77Tools
        uses: i3h/download-release-asset@v1.2.0
        with:
          owner: WolvenKit
          repo: CP77Tools
          tag: v.1.1.0.5
          file: Release_1.2.zip
          
      - name: Unzip CP77Tools
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: Release_1.2.zip
          pathTarget: CP77Tools/
          
      - run: tree /F
      
      - name: Clone dll dependency
        uses: actions/checkout@v2
        with:
          repository: Nats-ji/oo2ext
          token: ${{ secrets.PAT }}
          path: .\CP77Tools\Release\net5.0-windows\win-x64\
      
      - name: Rebuild Texture
        run: |
          .\CP77Tools\Release\net5.0-windows\win-x64\CP77Tools.exe rebuild -b -t --keep --unsaferaw -p ".\new-moon"
          
      - name: Pack archive
        run: |
          .\CP77Tools\Release\net5.0-windows\win-x64\CP77Tools.exe pack -p ".\new-moon"
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./*.archive

