# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100
      
      - name: Clone CP77Tool
        uses: actions/checkout@v2
        with:
          repository: WolvenKit/CP77Tools
          path: ./CP77Tools

      - name: Clean
        run: |
          cd .\CP77Tools
          dotnet clean ./CP77Tools.sln --configuration Release && dotnet nuget locals all --clear
          
      - name: Install dependencies
        run: |
          cd .\CP77Tools
          dotnet restore
      
      - name: Build
        run: |
          cd .\CP77Tools
          dotnet build --configuration Release --no-restore
          
      - name: Rebuild Texture
        run: |
          .\CP77Tools\CP77Tools\bin\Release\net5.0-windows\win-x64\CP77Tools.exe rebuild -b -t --keep --unsaferaw -p ".\new-moon"
          
      - name: Pack archive
        run: |
          .\CP77Tools\CP77Tools\bin\Release\net5.0-windows\win-x64\CP77Tools.exe pack -p ".\new-moon"
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./*.archive

